on:
  push:
    tags:
      # available only for tags like `v1.2.3` or `v1.2.3-rc1`
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

name: Release Draft
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: Create a Release Draft
        run: make release
        env:
          # this token is requried to create a release in the repository
          # For more detail, refer to https://docs.github.com/en/actions/reference/authentication-in-a-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Binary
        run: |
          ./dist/kubectl-sigstore-linux-amd64 version